version: '3'
services:
  java:
    build: 
      context : ./java
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  db:
    build: 
      context : ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: youtube
      POSTGRES_USER: ytb
      POSTGRES_PASSWORD: sheshGaming
    volumes:
      - db-data:/var/lib/postgresql/data