/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6.4/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://m2.dv8tion.net/releases")
    maven ("https://jitpack.io")
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.3-jre")
    
    // https://mvnrepository.com/artifact/org.json/json
    implementation("org.json:json:20090211")

    // jda
    implementation("net.dv8tion:JDA:5.0.0-beta.20")

    // google
    implementation("com.google.api-client:google-api-client:1.32.1")
    implementation("com.google.oauth-client:google-oauth-client-jetty:1.23.0")
    implementation("com.google.apis:google-api-services-youtube:v3-rev222-1.25.0")
    implementation("com.google.api-client:google-api-client-jackson2:1.28.1")

    // lava player
    implementation("com.github.idpromnut:lavaplayer:youtube_details_parse_bug-SNAPSHOT")
}

application {
    // Define the main class for the application.
    mainClass.set("discord_bot.Main")
}
